#!/usr/bin/env bash
# $1 = command to run, commands:
# - start: start Mongo container
# - status: get status of container, outputs "running" if Mongo server is running,
#           "stopped" if the Mongo container is stopped but still exists, and
#           "not found" if the Mongo container does not exist.
prog_dir=$(dirname $(realpath "$0"))
   
function die() {
    echo "mongo: $@" >&2
    exit 1
}

if [ -z "$CONTAINER_CLI" ]; then
    CONTAINER_CLI="sudo podman"
fi

container_name=dev-spotify-to-napster
container_tag="mongo:latest"

container_host_db_dir="$prog_dir/container-data/mongodb"
container_guest_db_dir="/data/db"
if ! mkdir -p "$container_host_db_dir" &> /dev/null; then
    die "Failed to create host container database directory"
fi

case "$1" in
    start)
	   case $($0 status) in
		  running) die "already running" ;;
		  stopped) $CONTAINER_CLI start "$container_name" ;;
		  "not found")
			 $CONTAINER_CLI run \
						 -d \
						 --net host \
						 -v "$container_host_db_dir:$container_guest_db_dir" \
						 --name "$container_name" \
						 "$container_tag"
			 if [[ "$?" != "0" ]]; then
				die "Failed to start"
			 fi
			 ;;
	   esac
	   ;;
    status)
	   if $CONTAINER_CLI ps | grep "$container_name" &> /dev/null; then
		  echo "running"
	   elif $CONTAINER_CLI ps -a | grep "$container_name" &> /dev/null; then
		  echo "stopped"
	   else
		  echo "not found"
	   fi
	   ;;
    stop)
	   case $($0 status) in
		  running)
			 $CONTAINER_CLI stop "$container_name"
			 $CONTAINER_CLI rm "$container_name"
			 ;;
		  stopped)
			 $CONTAINER_CLI rm "$container_name"
			 ;;
		  *) die "Cannot stop and remove mongo if not running" ;;
	   esac
	   ;;
    logs)
	   case $($0 status) in
		  running)
			 $CONTAINER_CLI logs -f "$container_name"
			 ;;
		  *) die "Cannot get logs if Mongo is not running" ;;
	   esac
	   ;;
    cli)
	   shift
	   $CONTAINER_CLI run -it --rm --net host "$container_tag" mongo $@
	   ;;
    *)
	   die "first argument must be \"start\", \"status\", \"stop\", \"logs\", \"cli\""
	   ;;
esac
